# Generated by Django 3.1.1 on 2020-11-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_name',
        ),
        migrations.AddField(
            model_name='newuser',
            name='address',
            field=models.TextField(blank=True, max_length=500, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
