# Generated by Django 3.1.1 on 2020-11-13 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201113_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 11, 13, 11, 10, 19, 747111, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
