# Generated by Django 3.1.1 on 2020-11-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('dob', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=25)),
            ],
        ),
    ]
