# Generated by Django 3.1.1 on 2020-11-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20201113_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
