# Generated by Django 3.1.1 on 2020-11-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20201113_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
